version: '2'

services:
  monitor:
    image: prom/prometheus:v2.36.2
    container_name: test-prometheus
    restart: always
    ports:
      - 9090:9090
      - 9100:9100
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./node_exporter-1.1.1.linux-amd64:/home/node_exporter
    networks:
      grafana-mysql_tmpnetwork:
        ipv4_address: 172.22.0.33

networks:
  grafana-mysql_tmpnetwork:
    #name: tmpnetwork
    external: true
